# 生成 PotatoDownload 端到端测试载荷（test_game.zip），并输出 base64 / size / sha256。
# index.html 中的 PAYLOAD 常量由本脚本的输出更新；载荷内容或结构变化后重新运行即可。
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$payloadDir = Join-Path $root 'payload'
New-Item -ItemType Directory -Force -Path $payloadDir | Out-Null
$zipPath = Join-Path $payloadDir 'test_game.zip'
if (Test-Path $zipPath) { Remove-Item $zipPath -Force }

Add-Type -AssemblyName System.IO.Compression
$fixedDate = [DateTimeOffset]::new(2026, 1, 1, 0, 0, 0, [TimeSpan]::Zero)

$stream = [System.IO.File]::Open($zipPath, [System.IO.FileMode]::CreateNew)
try {
    $zip = New-Object System.IO.Compression.ZipArchive($stream, [System.IO.Compression.ZipArchiveMode]::Create)
    try {
        $entries = [ordered]@{
            'game.exe'   = "PotatoDownload E2E test executable. Not a real game.`r`n"
            'readme.txt' = "PotatoDownload end-to-end test payload, generated by TestPlatform.`r`n"
        }
        foreach ($name in $entries.Keys) {
            $entry = $zip.CreateEntry($name, [System.IO.Compression.CompressionLevel]::Optimal)
            $entry.LastWriteTime = $fixedDate
            $writer = New-Object System.IO.StreamWriter($entry.Open())
            try { $writer.Write($entries[$name]) } finally { $writer.Dispose() }
        }
    } finally { $zip.Dispose() }
} finally { $stream.Dispose() }

$bytes = [System.IO.File]::ReadAllBytes($zipPath)
$base64 = [Convert]::ToBase64String($bytes)
$sha256Obj = [System.Security.Cryptography.SHA256]::Create()
try { $hashBytes = $sha256Obj.ComputeHash($bytes) } finally { $sha256Obj.Dispose() }
$sha256 = [System.BitConverter]::ToString($hashBytes).Replace('-', '').ToLowerInvariant()
[System.IO.File]::WriteAllText((Join-Path $payloadDir 'base64.txt'), $base64)
$json = @{ size = $bytes.Length; sha256 = $sha256; base64 = $base64 } | ConvertTo-Json -Compress
[System.IO.File]::WriteAllText((Join-Path $payloadDir 'payload.json'), $json, [System.Text.Encoding]::UTF8)
Write-Host "zip=$zipPath"
Write-Host "size=$($bytes.Length) sha256=$sha256 b64len=$($base64.Length)"
